### ISSUE TITLE
Nothing on the page

### ISSUE THREAD

**Issue by seemsindie** [wbkd/riotjs-startkit#1]
I do all the steps you specified, clone, npm i, and then i run dev server.
But all i get on page is white empty space, and only title is written on the tab.
In console there is no errors.

My npm version is 2.14.7 and node is v4.2.1.

**Comment by g-div** [comment]
Thanks!
The issue was caused by a breaking change to the riot API. 

Everything should works again now!
Let us know if you discover any other issue.
