### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by seemsindie** [wbkd/riotjs-startkit#2]
Not an issue but a question.
How would i go about adding third party stuff, like semantic-ui. I installed it with npm i --save semantic-ui
I have added jQuery like:

```
plugins: [
    new webpack.ProvidePlugin({
      riot: 'riot',
      $: "jquery",
      jQuery: "jquery"
    })
  ],
```

How would i go about including semantic.css and semantic.js inside project. 

I have css included included in index.js like:

```
import '../semantic/dist/semantic.css';
```

Is that the right way to include it, or there is other way.
And i also did the same for semantic.js
It seems that everything is loaded, but i most of plugins in semantic don't work, there is no error it's just not there or it doesn't work...

I am only asking for a guide on how to import stuff like that into project. I am new to webpack, it's unknown territory for me.

Thanks man

**Comment by seemsindie** [comment]
Well that thing was not working because i wan initializing jQuery plugin just in script tag but should have done it in this.on('mount', ...).

**Comment by g-div** [comment]
Yes, your `import` statements look good. Nice to hear that it's working now.

Sometimes importing dependencies that use different module definitions (AMD, CommonJS, ES6, UMD or even none of them) can become tricky. Webpack can easily handle AMD and CommonJS.

You may want to referr directly to [webpack](https://github.com/webpack/webpack) for similar issues.
